"""empty message

Revision ID: cae496bb4fcc
Revises: 
Create Date: 2022-05-26 17:53:36.997056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae496bb4fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=225), nullable=True),
    sa.Column('username', sa.String(length=225), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.Column('password_token', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
